app0/urls.py
from django.urls import path, include

from . import views

app_name = 'app0'

urlpatterns = [
    path('', views.index, name='index'),
    path('vis1', views.vis1, name='vis1'),
    path('vis2', views.vis2, name='vis2'),
    path('vis3', views.vis3, name='vis3'),
    path('vis4', views.vis4, name='vis4'),
    path('about', views.about, name='about'),
]

temblores/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app0.urls'))
]

app0/models.py
from django.db import models

# Create your models here.

app0/views.py
from django.shortcuts import render
from django.http import HttpResponse
from app0.Analisis import Vis1 as visualizacion1
from app0.Analisis import Vis2 as visualizacion2
from app0.Analisis import Vis3 as visualizacion3
from app0.Analisis import Vis4 as visualizacion4

def index(request):
    return render(request, 'app0/index.html', None)

def vis1(request):
    return visualizacion1.analizar(request)

def vis2(request):
    return visualizacion2.analizar(request)

def vis3(request):
    return visualizacion3.analizar(request)

def vis4(request):
    return visualizacion4.analizar(request)

def about(request):
    return render(request, 'app0/about.html', None)

app0/templates/app0/about.html
{% extends 'app0/base.html' %}

{% block content %}
  <!-- Page Content -->
  <header class="jumbotron my-4">
    <h2 class="display-4">Temblores</h2>
    <p class="lead">Temblores ONG is a non profit organisation that works for the
      defense of human rights in Colombia. We seek to promote comunitary processes
      of transformation and facilitate dialogues between the academie, the State,
      the public opinion and communities in order to expose violences against
      historically marginalized groups.</p>
  </header>

{% endblock %}

app0/templates/app0/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  {% load static %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Visualizacion Temblores</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'app0/css/bootstrap.min.css' %}" rel="stylesheet">



  <!-- Custom styles for this template -->
  <link href="{% static 'app0/css/style.css' %}" rel="stylesheet">

  <!-- Add Favicon to page -->
  <link rel="icon" href="{% static 'app0/img/logo_temblores.ico' %}" type="image/x-icon">

  <!-- Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- D3 -->
  <script src="//d3js.org/d3.v5.min.js"></script>

  <!-- Ajax -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/d3-queue/3.0.4/d3-queue.min.js"></script>

  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'app0/js/jquery.slim.min.js' %}"></script>

  <!-- Bootstrap tooltips JS -->
  <script type="text/javascript" src="{% static 'app0/js/popper.min.js' %}"></script>

  <!-- Bootstrap core JS -->
  <script type="text/javascript" src="{% static 'app0/js/bootstrap.min.js' %}"></script>

  <!-- Charts.js -->
  <script src="{% static 'app0/js/node_modules/chart.js/dist/Chart.js' %}"></script>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <img class="navbar-brand" width="65" height="75" src="{% static 'app0/img/logo_temblores.ico' %}" alt="">
      <a class="navbar-brand" href="https://www.temblores.org/">Temblores</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'app0:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.temblores.org/sobre-nosotros">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  {% block content %}
  {% endblock %}
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <div class="row" style="justify-content:center">
          <a class="btn" href="https://www.facebook.com/tembloresong/"><i class="fa fa-facebook-square" style="font-size:48px;color:white"></i></a>
          <a class="btn" href="https://twitter.com/tembloresong?lang=en"><i class="fa fa-twitter-square" style="font-size:48px;color:white"></i></a>
          <a class="btn" href="https://www.instagram.com/tembloresong/"><i class="fa fa-instagram" style="font-size:48px;color:white"></i></a>
      </div>
      <p class="m-0 text-center text-white">Copyright &copy; Temblores 2019</p>
      <p class="m-0 text-center text-white"><b>Fuente:</b> Sistema de Información de Clínica y Odontología Forense.
        SICLICO Instituto Nacional de Medicina Legal y Ciencias Forenses - INMLCF / Grupo Centro de Referencia Nacional sobre Violencia – GCRNV.</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'app0/js/jquery.min.js' %}"></script>
  <script src="{% static 'app0/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

app0/templates/app0/index.html
{% extends 'app0/base.html' %}

{% block content %}
{% load static %}
  <!-- Page Content -->
  <div class="container">

    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <h2 class="display-4">Segundo reporte de violencia por partte de la fuerza pública</h2>
      <p class="lead">Los datos aquí expuestos fueron adquiridos por derecho de petición
        a Medicina Legal y cubren el periodo de <b>Enero 2017</b> a <b>Diciembre 2018</b>.</p>
      <a href="https://www.temblores.org/sistema-callejero" class="btn btn-outline-secondary">Ver reporte</a>
    </header>

    <!-- Page Features -->
    <div class="row text-center" style="margin-top:50px; margin-bottom:100px">

      <div class="col-lg-3 col-md-6 mb-4">
        <a href="{% url 'app0:vis1' %}">
          <img style="width: 250px; height: 350px" src="{% static 'app0/img/Fecha_hora.png' %}" alt="">
        </a>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <a href="{% url 'app0:vis2' %}">
          <img style="width: 250px; height: 350px" src="{% static 'app0/img/sexo-edad.png' %}" alt="">
        </a>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <a href="{% url 'app0:vis3' %}">
          <img style="width: 250px; height: 350px" src="{% static 'app0/img/geografia.png' %}" alt="">
        </a>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <a href="{% url 'app0:vis4' %}">
          <img style="width: 250px; height: 350px" src="{% static 'app0/img/contexto.png' %}" alt="">
        </a>
      </div>
    </div>

  </div>
  <!-- /.container -->
{% endblock %}

app0/templates/app0/vis1.html
{% extends 'app0/base.html' %}

{% block content %}

{% load static %}

<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>

<!-- CSS for this view -->
<!-- <link rel="stylesheet" href="{% static 'app0/css/vis1.css' %}"> -->

<div class="container">

  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">
    <h2 class="display-4">Denuncias de violencia cometida por parte de la fuerza publica.</h2>
    <h4 class="lead"> Datos entre <b>Enero 2017</b> y <b>Diciembre 2018</b>. </h4>
    <p class="lead">En la distribución de la derecha, seleccionar los meses que se desean explorar.
      Es posible interactuar con las leyendas de las distribuciones para escoger el dataset que se desea.</p>
  </header>


  <dataV data-v="{{ data_v }}"></dataV>
  <dataH data-h="{{ data_h }}"></dataH>


  <!-- Page Features -->
  <div class="text-center">
    <div class="row align-items-center" style="vertical-align:middle">
      <div class="col-md-8" >
        <div class="row align-items-center">
          <canvas
          id="details_chart_hour"
          style="max-width: 600px;
                height: 400px;
                margin-right: 10px;
                margin-top: 50px;">
          </canvas>
        </div>
      </div>
      <div class="col-md-2" id="selector_chart">
      </div>
    </div>
    <div class="row align-items-center">
      <canvas
      id="details_chart_day"
      style="
            height: 400px;
            margin-right: 20px;
            margin-bottom: 100px">
      </canvas>
    </div>
  </div>

</div>


<script src="{% static 'app0/js/vis1.js' %}"></script>

{% endblock %}

app0/templates/app0/vis2.html
{% extends 'app0/base.html' %}

{% block content %}

{% load static %}
<script src="https://d3js.org/d3.v3.min.js"></script>

<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>

<!-- CSS for this view -->
<link rel="stylesheet" href="{% static 'app0/css/vis2.css' %}">

<div class="container">

  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">
    <h2 class="display-4">Denuncias de violencia cometida por parte de la fuerza publica</h2>
    <h4 class="lead"> Datos entre <b>Enero 2017</b> y <b>Diciembre 2018</b>. </h4>
    <p class="lead">En la distribución de la derecha, seleccionar los rangos de edad que desea explorar.
    En la grafica de la izquierda, es posible interactuar con la leyenda para seleccionar información se desea visualizar.</p>
  </header>


  <dataV violence-vals="{{ data_v }}"></dataV>
  <dataH homicide-vals="{{ data_h }}"></dataH>

  <!-- Page Features -->
  <div class="text-center">
    <div class="row align-items-center">
      <div class="col-md-8" >
        <canvas id="details_chart" style="max-width: 700px; height: 500px"></canvas>
      </div>
      <div class="col-md-2" id="selector_chart">
        <div id="drop" align=center></div>
      </div>
    </div>
  </div>

</div>
<script src="{% static 'app0/js/vis2.js' %}"></script>

{% endblock %}

app0/templates/app0/vis3.html
{% extends 'app0/base.html' %}

{% block content %}

{% load static %}

<!-- CSS for this view -->
<!-- <link rel="stylesheet" href="{% static 'app0/css/vis3.css' %}"> -->

<script src="https://unpkg.com/d3-simple-slider"></script>

<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>

<!-- D3 -->
<script src="https://d3js.org/d3.v3.min.js"></script>

<!-- data -->
  <data
    Geojson="{% static 'app0/json/Colombia.geo.json' %}"
    totals_v="{{ totals_v }}"
    totals_h="{{ totals_h }}"
    data_v="{{ data_v }}"
    data_h="{{ data_h }}"
    data_p="{{ pop_data }}"
  ></data>




<div class="container">

  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">
    <h2 class="display-4">Denuncias de violencia cometida por parte de la fuerza publica.</h2>
    <h4 class="lead"> Datos entre <b>Enero 2017</b> y <b>Diciembre 2018</b>. </h4>
    <p class="lead">El mapa muestra con color el numero de incidentes violentos, normalizados por densidad de poblacion de cada departamento.
      Seleccionar el area del mapa que se quiere explorar.</p>
  </header>
</div>

<div style="justify-content:center">
  <div class="row">
    <div class="col">
        <svg id="map"></svg>
    </div>
    <div class="col">
        <canvas
        id="dept_details"
        style="
              max-width: 800px;
              height: 600px;
              margin-right: 100px;
              justify-content:left
              ">
        </canvas>
    </div>
  </div>
</div>

<script src="{% static 'app0/js/vis3.js' %}"></script>

{% endblock %}

app0/templates/app0/vis4.html
{% extends 'app0/base.html' %}

{% block content %}

{% load static %}

<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>

<!-- data -->
  <data
    mecanismoV="{{ mecanismoV }}"
    mecanismoH="{{ mecanismoH }}"
    causaH="{{ causaH }}"
    ocupacionH="{{ ocupacionH }}"
    ocupacionV="{{ ocupacionV }}"
    minoriaV="{{ minoriaV }}"
    minoriaH="{{ minoriaH }}"
  ></data>

<!-- CSS for this view -->
<!-- <link rel="stylesheet" href="{% static 'app0/css/vis1.css' %}"> -->

<div class="container">

  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">
    <h2 class="display-4">Denuncias de violencia cometida por parte de la fuerza publica.</h2>
    <h4 class="lead"> Datos de contexto del hecho entre <b>Enero 2017</b> y <b>Diciembre 2018</b>. </h4>
  </header>
</div>

  <!-- Page Features -->
<div class="row">
    <div class="col" style="margin-bottom:50px"><canvas id="causaH"></canvas></div>
    <div class="col" style="margin-bottom:50px"><canvas id="mecanismoV"></canvas></div>
    <div class="w-100"></div>
    <div class="col" style="margin-bottom:50px"><canvas id="minoriaH"></canvas></div>
    <div class="col" style="margin-bottom:50px"><canvas id="minoriaV"></canvas></div>
    <!-- <div class="w-100"></div>
    <div class="col" style="margin-bottom:50px"><canvas id="ocupacionH"></canvas></div>
    <div class="col" style="margin-bottom:50px"><canvas id="ocupacionV"></canvas></div> -->

</div>




<script src="{% static 'app0/js/vis4.js' %}"></script>

{% endblock %}